format = "$directory$git_branch$git_status$line_break$character"
right_format = "$cmd_duration ($username(@$hostname))"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold mauve)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[directory]
style = "bold blue"
truncate_to_repo = false

[git_branch]
style = "bold purple"

[username]
format = "[$user]($style)"
style_root = "red dimmed"
style_user = "yellow dimmed"

[hostname]
format = "[$hostname]($style)"
style = "green dimmed"
